name: Test notifications

on:
  push:
    branches:
      - test

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: 📣 Send teams notification
        uses: TWiStErRob/msteams-message-card-action@node20
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK }}
          message: Hello world!

      - name: 🪣 Set env vars
        if: ${{ always() }}
        run: |
          echo "MY_SPECIAL_BUTTON=Cool https://this-is-so.cool/" >> $GITHUB_ENV

      - name: 📣 Send teams notification
        if: ${{ always() }}
        uses: TWiStErRob/msteams-message-card-action@node20
        env:
          MY_AWESOME_BUTTON: Awesome https://this-is-so.awesome/
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK }}
          title: Hello world!
          message: <p>This is my <strong>awesome message!</strong></p>
          color: ff69b4
          buttons: |
            Click here! https://whatever.com/foo/
            Or here… https://somewhere.com/bar/
            This button will not be shown as it has no target URL
            https://no-label-no-button.com/
            ${{ env.MY_SPECIAL_BUTTON }}
            ${{ env.MY_AWESOME_BUTTON }}
